services:
  db-void:
    image: mysql:5.6.51
    container_name: lead_db_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql
    command: mysqld
    ports:
      - "3306:3306"
    restart: on-failure:3
    volumes:
      - lead-dbdata:/var/lib/mysql

volumes:
  lead-dbdata: